<Project Sdk="Godot.NET.Sdk/4.5.2">
  <PropertyGroup>
    <!-- REŠENJE: Prelazimo na net10.0 da u potpunosti iskoristimo instalirani .NET 10 SDK -->
    <TargetFramework>net9.0</TargetFramework>
    <!-- Ako gradnja gađa Android, dodajemo oznaku GODOT_ANDROID u listu konstanti -->
    <DefineConstants Condition="'$(GodotTargetPlatform)' == 'android'">$(DefineConstants);GODOT_ANDROID</DefineConstants>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    
    <!-- ŠTIT PROTIV CRVENILA: Sve privremene Android fajlove bacamo u 
         izolovani podfolder, čime tvoj VSCodium radni prostor na desktopu ostaje u savršenom miru! -->
    <BaseIntermediateOutputPath Condition=" '$(GodotTargetPlatform)' == 'android' ">obj/android/</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ChessDotNet" Version="1.0.0" />
    <!-- Uvoz zvaničnog WebAssembly runtime-a kompatibilnog sa .NET 10 -->
    <PackageReference Include="Wasmtime" Version="34.0.2" />
  </ItemGroup>

  <!-- Bezbedno pakovanje Stockfish-a unutar aplikacije kao Embedded Resource -->
  <ItemGroup>
    <EmbeddedResource Include="data\stockfish.wasm">
      <LogicalName>stockfish.wasm</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
